# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='OembedVideoPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_oembed_oembedvideoplugin', serialize=False, to='cms.CMSPlugin')),
                ('oembed_url', models.URLField(verbose_name='url')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('autoplay', models.BooleanField(default=False)),
                ('show_related', models.BooleanField(default=False, help_text='hiding related videos is not supported by Vimeo (you need vimeo plus)')),
                ('loop', models.BooleanField(default=False, help_text='looping is not supported by YouTube')),
                ('type', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.TextField(blank=True, default='')),
                ('html', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
